var express = require('express');
var homeController = require("../controllers/homecontrollers/index");
var homeActivites = require("../controllers/homecontrollers/homeActivites");
var router = express.Router();
let uploads = require("../config/multer");
router.get("/", homeController.homePage);
router.get("/login", homeController.renderLoginPage);
router.post("/login", homeController.login);
router.post("/post", uploads.uploadPostPhoto.single('photo'), homeActivites.posting);
router.post("/comment", homeActivites.commenting);
router.post("/signup", homeController.processSignUp);
module.exports = router;